name: Check

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        with:
          script: |
            const { HEAD_SHA } = process.env;
            const [owner, repo] = ["clearloop", "actions"]

            const { data } = await github.rest.checks.create({
              owner,
              repo,
              name: "Build",
              head_sha: HEAD_SHA,
              details_url: "https://github.com/gear-tech/gear/actions/runs/5887617336/job/15967292456"
            });

            console.log(data);

            const { data: data2 } = await github.rest.checks.update({
              owner,
              repo,
              check_run_id: data.id,
              details_url: "https://github.com/gear-tech/gear/actions/runs/5887617336/job/15967292456"
            })

            console.log(data2);
